### Project specific config ###
language: generic

env:
  global:
    - APM_TEST_PACKAGES="linter"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"
    - PATH=/opt/python/3.7.1/bin:$PATH

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

before_install:
  - python --version
  - pip install --upgrade pip

  # command to install dependencies
install:
  - pip install -U lizard

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
